### ISSUE TITLE
arm64 container?

### ISSUE THREAD

**Issue by danielchalef** [getmetal/motorhead#44]
Do you have plans for building an arm64 container? It would significantly aid local development with motorhead as backend memory.

**Comment by Czechh** [comment]
yeah - I don't see why not! Will look into it.

Curious how it would significantly aid local development?

**Comment by danielchalef** [comment]
When developing an app using Motorhead memory, it would be useful to be able to run the full setup locally rather than using a remote staging Motorhead server. Many of us use MacBooks, hence the arm64 request. It might also be nice to be able to deploy Motorhead to cheap arm64 cloud instances.

**Comment by Czechh** [comment]
I develop using an M1 mackbook. And I'm using `docker-compose` to run Motorhead + Readisearch locally.

**Comment by danielchalef** [comment]
Are you successfully using Rosetta emulation? I attempted to do so and got 500 errors on a number of endpoints. I did not dig too deep into what was happening as I assumed emulation was breaking.

**Comment by Czechh** [comment]
Would appreciate to see what you're seeing.

No rosetta needed. Just using `docker-compose build && docker-compose up`.

The image getting build in GH packages I haven't tested locally. But since you're building the docker image from scratch with the Dockerfile, it should be working for you if you run it in M1 or x86.  This becomes an issue if you use the hosted image and it's not compatible, but building it from your computer should work.

So 5xx issues might be something else and would love to look into it.

**Comment by Czechh** [comment]
Ok - I'll get an ARM64 image out soon. Thanks for the feedback!

**Comment by danielchalef** [comment]
Which container are you running on your MacBook M1?

**Comment by Czechh** [comment]
I'm using the projects `docker-compose` you can replicate by cloning this repo and running `docker-compose build && docker-compose up`.

**Comment by danielchalef** [comment]
For some reason, compiling using the repo Dockerfile failed. See above.

**Comment by Czechh** [comment]
Just used this `docker-compose` and it worked.

```yaml
version: '3'
services:
  motorhead:
    image: ghcr.io/getmetal/motorhead:v1.0.1
    ports:
      - '8080:8080'
    links:
      - redis
    environment:
      PORT: 8080
      MOTORHEAD_LONG_TERM_MEMORY: 'true'
      REDIS_URL: 'redis://redis:6379'
    env_file:
      - .env

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
```

Here with a M1 mack - not sure why this isn't working for you 🤔  - Here I didn't have to build any images.
